# Generated by Django 4.0 on 2022-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=30, unique=True)),
                ('Company_name', models.CharField(max_length=30)),
                ('Owner_Email_Address', models.CharField(max_length=50)),
                ('AdminPass', models.CharField(max_length=50)),
            ],
        ),
    ]
