# Generated by Django 4.0 on 2022-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminw', '0003_alter_items_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Product_Id',
            field=models.IntegerField(unique=True),
        ),
    ]
