# Generated by Django 4.0 on 2022-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminw', '0005_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Product_Id',
            field=models.IntegerField(),
        ),
    ]
